# **Dataset** : *Diabetes 130-US Hospitals for Years 1999–2008*

**About** *: It is a real-world healthcare dataset of 101,766 rows × 50 columns*

**Objective** : *To perform comprehensive data cleaning and preprocessing on the diabetic patient dataset by identifying and handling missing values, correcting inconsistencies, removing irrelevant features, and preparing a high-quality dataset for further analysis*

**Dataset Description** : *This dataset contains information collected from diabetic patients admitted to 130 US hospitals between 1999 and 2008. It includes patient demographics, admission details, diagnoses, medications, laboratory procedures, and hospital readmission status.*

*The preprocessing steps performed in this notebook will ensure the dataset is accurate, consistent, and ready for further analysis.*



# **Environment Setup and load the dataset**

In [19]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sn

# Display Settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

# Plot Style
plt.style.use('ggplot')
sns.set_palette("Set2")

# **Load Dataset**

In [3]:
# Load the dataset
df = pd.read_csv("diabetic_data.csv")

# Load mapping file
mapping = pd.read_csv("IDS_mapping.csv")

# **Basic understanding regarding the dataset**

In [4]:
print("Diabetic Dataset Shape:", df.shape)
print("Mapping Dataset Shape:", mapping.shape)

Diabetic Dataset Shape: (101766, 50)
Mapping Dataset Shape: (67, 2)


In [5]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO


In [6]:
mapping.head()

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Not Available


In [7]:
print(df.columns)

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')


In [8]:
print(mapping.columns)

Index(['admission_type_id', 'description'], dtype='object')


In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766 non-null  int64 
 14  num_

In [11]:
mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   admission_type_id  65 non-null     object
 1   description        62 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB


In [13]:
# Statistical summary
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000


In [14]:
df.sample(5, random_state=42)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
35956,110939484,19274094,Caucasian,Female,[70-80),?,1,1,6,11,UN,InternalMedicine,68,0,20,0,0,0,250.8,599,263,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
60927,170328306,65634327,Caucasian,Male,[50-60),?,1,1,1,1,HM,?,20,0,7,0,0,0,780,427,E941,8,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
79920,245688426,100657359,Caucasian,Female,[60-70),?,3,6,1,4,HM,?,21,3,23,1,0,2,715,733,724,7,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
50078,150826224,83144448,Caucasian,Male,[30-40),?,2,1,1,12,CP,Gastroenterology,28,0,19,0,0,1,494,277,117,7,NaN,NaN,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
44080,135993852,65234214,AfricanAmerican,Female,[60-70),?,1,2,7,1,?,?,21,0,6,0,0,0,403,584,428,7,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,<30


# **Data Quality Assessment**

In [15]:
# Missing values
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": (df.isnull().sum()/len(df))*100
})

missing[missing["Missing Values"]>0].sort_values(
    by="Percentage (%)",
    ascending=False
)

,Missing Values,Percentage (%)
max_glu_serum,96420,94.746772
A1Cresult,84748,83.277322


In [16]:
# Duplicate rows
df.duplicated().sum()

np.int64(0)

In [17]:
# Unique values
df.nunique()

,0
encounter_id,101766
patient_nbr,71518
race,6
gender,3
age,10
weight,10
admission_type_id,8
discharge_disposition_id,26
admission_source_id,17
time_in_hospital,14


In [18]:
# Check '?' values
(df == '?').sum()

,0
encounter_id,0
patient_nbr,0
race,2273
gender,0
age,0
weight,98569
admission_type_id,0
discharge_disposition_id,0
admission_source_id,0
time_in_hospital,0


# **Cleaning Notes**

The following preprocessing steps will be performed to improve data quality and prepare the dataset for further analysis.

1. **encounter_id:** Check for missing values. Since it is a unique identifier, remove it if it is not required for analysis.

2. **patient_nbr:** Check for missing values. Since it uniquely identifies patients, remove it if it is not required for analysis.

3. **race:** Replace `"?"` with `NaN`, handle missing values using the mode, and encode categorical values if required.

4. **gender:** Remove `"Unknown/Invalid"` records and encode `Male` and `Female` into numerical values.

5. **age:** Convert age ranges (e.g., `[0-10)`, `[10-20)`) into numerical midpoint values.

6. **weight:** Since the column contains a very high percentage of missing values, remove it from the dataset.

7. **admission_type_id:** Verify data type, check for missing values, and map IDs using the mapping dataset if required.

8. **discharge_disposition_id:** Verify data type, check for missing values, and map IDs if required.

9. **admission_source_id:** Verify data type, check for missing values, and map IDs if required.

10. **time_in_hospital:** Check for invalid or missing values and ensure the data type is appropriate.

11. **payer_code:** Remove the column due to the large number of missing values.

12. **medical_specialty:** Replace `"?"` with `NaN`; if the percentage of missing values is too high, remove the column; otherwise, impute missing values.

13. **num_lab_procedures:** Check for missing or invalid values.

14. **num_procedures:** Check for missing or invalid values.

15. **num_medications:** Check for missing or invalid values.

16. **number_outpatient:** Check for missing values and validate the data.

17. **number_emergency:** Check for missing values and validate the data.

18. **number_inpatient:** Check for missing values and validate the data.

19. **diag_1:** Replace missing values with `"Unknown"` and clean diagnosis codes if necessary.

20. **diag_2:** Replace missing values with `"Unknown"` and clean diagnosis codes if necessary.

21. **diag_3:** Replace missing values with `"Unknown"` and clean diagnosis codes if necessary.

22. **max_glu_serum:** Encode categorical values into numerical labels.

23. **A1Cresult:** Encode categorical values into numerical labels.

24. **Medication Columns** (`metformin`, `repaglinide`, `nateglinide`, ..., `insulin`): Encode medication status (`No`, `Steady`, `Up`, `Down`) into numerical values.

25. **change:** Encode `No` and `Ch` into numerical values.

26. **diabetesMed:** Encode `No` and `Yes` into numerical values.

27. **readmitted:** Encode target classes (`NO`, `>30`, `<30`) into numerical labels (0, 1, 2).

28. **Final Validation:** Verify missing values, duplicate records, data types, and dataset dimensions before exporting the cleaned dataset.

# **Data Cleaning**

## **1. encounter_id**

In [21]:
# check data type
df["encounter_id"].dtype

dtype('int64')

In [22]:
# Check Missing Values
df["encounter_id"].isnull().sum()

np.int64(0)

In [23]:
# Check Duplicate Values
df["encounter_id"].duplicated().sum()

np.int64(0)

## **2. patient_nbr**

In [25]:
# Check Data Type
df["patient_nbr"].dtype

dtype('int64')

In [27]:
# Check Missing Values
df["patient_nbr"].isnull().sum()

np.int64(0)

In [28]:
# Check Duplicate Values
df["patient_nbr"].duplicated().sum()

np.int64(30248)

In [29]:
# Convert Data Type
df["patient_nbr"] = df["patient_nbr"].astype("int64")

## **3. race**

In [30]:
# Check Data Type
df["race"].dtype

dtype('O')

In [31]:
# Check Unique Values
df["race"].unique()

array(['Caucasian', 'AfricanAmerican', '?', 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [32]:
# Check Missing Values
df["race"].isnull().sum()

np.int64(0)

In [33]:
# Replace '?' with NaN and Fill Missing Values with Mode
import numpy as np

df["race"] = df["race"].replace("?", np.nan)

mode_race = df["race"].mode()[0]

df["race"] = df["race"].fillna(mode_race)

In [35]:
# Verify Missing Values
df["race"].isnull().sum()

np.int64(0)

In [36]:
# Convert Categorical Values into Numerical Values
race_map = {
    "Caucasian": 1,
    "AfricanAmerican": 2,
    "Asian": 3,
    "Hispanic": 4,
    "Other": 5
}

df["race"] = df["race"].map(race_map)

In [37]:
# Verify Encoding
df["race"].unique()

array([1, 2, 5, 3, 4])

## **4. age**

In [38]:
# Check Data Type
df["age"].dtype

dtype('O')

In [39]:
# Check Unique Values
df["age"].unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [40]:
# Check Missing Values
df["age"].isnull().sum()

np.int64(0)

In [41]:
# Convert Age Groups into Numerical Values
age_map = {
    "[0-10)": 5,
    "[10-20)": 15,
    "[20-30)": 25,
    "[30-40)": 35,
    "[40-50)": 45,
    "[50-60)": 55,
    "[60-70)": 65,
    "[70-80)": 75,
    "[80-90)": 85,
    "[90-100)": 95
}

df["age"] = df["age"].map(age_map)

In [42]:
# Verify Conversion
df["age"].unique()

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [43]:
# Check Data Type After Conversion
df["age"].dtype

dtype('int64')

## **5. admission_type_id**


In [44]:
# Check Data Type
df["admission_type_id"].dtype

dtype('int64')

In [45]:
# Check Missing Values
df["admission_type_id"].isnull().sum()

np.int64(0)

In [46]:
# Check Unique Values
df["admission_type_id"].unique()

array([6, 1, 2, 3, 4, 5, 8, 7])

## **6. discharge_disposition_id**

In [47]:
# Check Data Type
df["discharge_disposition_id"].dtype

dtype('int64')

In [48]:
# Check Missing Values
df["discharge_disposition_id"].isnull().sum()

np.int64(0)

In [49]:
# Check Unique Values
df["discharge_disposition_id"].unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

## **7. admission_source_id**


In [50]:
# Check Data Type
df["admission_source_id"].dtype

dtype('int64')

In [51]:
# Check Missing Values
df["admission_source_id"].isnull().sum()

np.int64(0)

In [52]:
# Check Unique Values
df["admission_source_id"].unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3, 17,  8,  9, 14, 10, 22, 11, 25, 13])

## **8. Diagnosis Columns (diag_1, diag_2, diag_3)**

In [54]:
# Check Missing Values
df[["diag_1", "diag_2", "diag_3"]].isnull().sum()

,0
diag_1,0
diag_2,0
diag_3,0


In [55]:
# Check Unique Values
df["diag_1"].unique()
df["diag_2"].unique()
df["diag_3"].unique()

array(['?', '255', 'V27', '403', '250', 'V45', '38', '486', '996', '197',
       '250.6', '427', '627', '414', '416', '714', '428', '582', 'V43',
       '250.01', '263', '250.42', '276', '482', '401', '250.41', '585',
       '781', '278', '998', '568', '682', '618', '250.02', '305', '707',
       '496', '599', '715', '424', '518', '553', '794', '411', 'V42',
       '531', '511', '490', '562', '250.8', '250.7', '250.52', '784',
       '491', '581', '420', '8', '724', '730', '789', '131', '250.82',
       '999', '41', '493', '250.03', '753', '786', '529', 'E888', '425',
       '595', '303', '560', '711', '492', '332', '296', '438', '362',
       '250.4', '654', '244', 'V70', '737', '625', '681', '250.51', '404',
       'V10', '810', '280', '440', '785', '588', '569', '272', '997',
       '250.43', '918', '584', '54', '788', '426', '722', '250.92', '196',
       '461', '535', '787', '891', '284', '458', '648', '780', '182',
       '285', '593', '413', '664', '564', '201', '356', 'V15', '2

In [56]:
# Replace '?' with NaN and Fill Missing Values

df["diag_1"] = df["diag_1"].replace("?", np.nan)
df["diag_1"] = df["diag_1"].fillna("Unknown")

df["diag_2"] = df["diag_2"].replace("?", np.nan)
df["diag_2"] = df["diag_2"].fillna("Unknown")

df["diag_3"] = df["diag_3"].replace("?", np.nan)
df["diag_3"] = df["diag_3"].fillna("Unknown")

In [57]:
# Verify Missing Values
df[["diag_1", "diag_2", "diag_3"]].isnull().sum()

,0
diag_1,0
diag_2,0
diag_3,0


## **9. Binary Columns**

In [58]:
# Check Unique Values
df["change"].unique()
df["diabetesMed"].unique()

array(['No', 'Yes'], dtype=object)

In [59]:
# Convert Binary Values into Numerical Values
binary_map = {
    "No": 0,
    "Yes": 1,
    "Ch": 1
}

df["change"] = df["change"].map(binary_map)
df["diabetesMed"] = df["diabetesMed"].map(binary_map)

In [60]:
# Verify Conversion
df["change"].unique()
df["diabetesMed"].unique()

array([0, 1])

## **10. Target Column**

In [61]:
# Check Data Type
df["readmitted"].dtype

dtype('O')

In [62]:
# Check Unique Values
df["readmitted"].unique()

array(['NO', '>30', '<30'], dtype=object)

In [63]:
# Check Missing Values
df["readmitted"].isnull().sum()

np.int64(0)

In [64]:
# Convert Target Values into Numerical Labels
target_map = {
    "NO": 0,
    ">30": 1,
    "<30": 2
}

df["readmitted"] = df["readmitted"].map(target_map)

In [65]:
# Verify Conversion
df["readmitted"].unique()

array([0, 1, 2])

In [68]:
# Check Data Type After Conversion
df["readmitted"].dtype

dtype('int64')

# **Final Validation**

In [70]:
# Missing Values
df.isnull().sum()

,0
encounter_id,0
patient_nbr,0
race,0
gender,0
age,0
weight,0
admission_type_id,0
discharge_disposition_id,0
admission_source_id,0
time_in_hospital,0


In [71]:
# Duplicate Rows
df.duplicated().sum()

np.int64(0)

In [72]:
# Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  int64 
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  int64 
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766 non-null  int64 
 14  num_

In [73]:
# Dataset Shape
df.shape

(101766, 50)

In [74]:
# First Five Rows
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,1,Female,5,?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,Unknown,Unknown,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,0,0,0
1,149190,55629189,1,Female,15,?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,1,1,1
2,64410,86047875,2,Female,25,?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,0,1,0
3,500364,82442376,1,Male,35,?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,1,1,0
4,16680,42519267,1,Male,45,?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,1,1,0


# **Save Clean Dataset**

In [75]:
df.to_csv("cleaned_diabetic_data.csv", index=False)

## Summary

- Loaded the diabetes dataset and mapping dataset.
- Explored the dataset to understand its structure.
- Identified missing values and duplicate records.
- Cleaned categorical and numerical columns.
- Replaced invalid values ('?') with appropriate values.
- Encoded categorical variables into numerical form.
- Removed columns with excessive missing values.
- Validated the cleaned dataset.
- Exported the final cleaned dataset for further analysis and machine learning.
